### ISSUE TITLE
Compatibility with JDK 6+

### ISSUE THREAD

**Issue by jkwiecien** [denley/courier#19]
I'm not exactly sure if this is due to apt plug-in anymore, but to be sure I started new project with just a couple of dependdencies. I managed to get the same error I'm now getting on my regular project with courier 1.0.2

Could you check it out? 

Here is the repo of test project I mentioned: https://github.com/jkwiecien/CourierAptTest

The exact error I get when rebuilding the project is: ```Error:Execution failed for task ':app:compileDebugJava'.> java.lang.NoSuchMethodError: javax.lang.model.element.Element.getAnnotationsByType(Ljava/lang/Class;)[Ljava/lang/annotation/Annotation;```

An error won't appear if you don't have any courier annotations in the project.

**Comment by denley** [comment]
Your test project compiles and runs just fine for me!

![device-2015-03-27-060448](https://cloud.githubusercontent.com/assets/1012150/6855349/356c4b48-d447-11e4-99ba-1697f13b3e8e.png)

**Comment by denley** [comment]
I see the problem. The [`getAnnotationsByType` method was only added in java 8](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/AnnotatedConstruct.html#getAnnotationsByType-java.lang.Class-). You must be running an older version of the JDK (6 or 7).

There's probably a way for Courier to work without this method, and since Android only requires java 6 I'll take this on board as a compatibility issue.

**Comment by jkwiecien** [comment]
I'm confused, is java8 supported by android?

**Comment by denley** [comment]
No, it's not. Android supports java 7 (since build-tools version 19. java 6 before that). 

But the error you are receiving is from the annotation processor (compiler) not from Android. The annotation processor is pure java. In fact, `javax.lang.model.element.Element` doesn't exist at all in Android (Android doesn't include anything in `javax.*`).

The annotation processor can use java 8 since it is running on your computer not on your Android device. You can install java 8 without breaking anything. It can still compile against java 7 for your Android code.

**Comment by jkwiecien** [comment]
How do you use java8 with Android Studio? My app won't run if I just set JDK path in module settings to java8. If it's set to java7 I get the mentioned error. Even if I set java8 as jdk for my machine:
```
➜  ~  java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
```

**Comment by denley** [comment]
> My app won't run
This is way too vague for me to be able to help you troubleshoot.

I've just made the fix for JDK 7+ support, so hopefully that fixes your issue. `compile 'me.denley.courier:courier:1.0.3'` should work with JDK 7.

I couldn't go as far as JDK 6, since Android Studio requires JDK 7, but I've set the source to compile for java 6 to maintain support for older Android versions.

**Comment by jkwiecien** [comment]
JDK7 sounds fine, grat thanks, I'm struggling for days with this, since I'm so excited with this library of yours :)

**Comment by denley** [comment]
No worries. I know how frustrating build errors can be. Gradle itself is a pretty steep learning curve. Thanks for helping me make courier more robust and compatible.

I'll close this issue now since I think it's fixed, but feel free to reopen it or keep commenting if something is still not working.
