### ISSUE TITLE
"Missing Annotations?"

### ISSUE THREAD

**Issue by ChrisOwen101** [denley/courier#21]
If you add Courier.startReceiving() and Courier.StopReceiving() to your code but do not use any annotations then it throws this error and force closes the app:

     Caused by: java.lang.IllegalStateException: Courier not found for nimbletank.asoswearable.Activities.MoreInformationActivity. Missing annotations

Could this restriction be removed? Simply because its a bit annoying if you forget to remove them when you're programming.

**Comment by denley** [comment]
Hi Chris, thanks for using Courier.

I can see how it's a little annoying in your case, but there are a few other cases where this error might also occur:
* The programmer has forgotten to annotate a field/method
* The annotation processor has not run properly at compile time, due to a build configuration error
* Missing ProGuard configuration

In these three instances it is better to crash with a message than to silently fail, as things will not work as intended. Since there's no way to differentiate between these cases at runtime, I think its best to leave the error message there.
