### ISSUE TITLE
 StreamCorruptedException when using Bitmap as fields

### ISSUE THREAD

**Issue by timrijckaert** [denley/courier#26]
Hiya, 

I have following class which I want to send to the Android Wear watch.

```java
@Deliverable
public class Match {

    String id;
    Bitmap homeTeamLogo;

    public Match(String id, Bitmap homeTeam) {
        this.id = id;
        this.homeTeam = homeTeam;
    }

}
```
I use this code to send it to the service

```java
Match wm = new Match(
                    matchDTO.id(),
                    bitmap
            );
Courier.deliverMessage(GcmReceiverService.this, Constant.WEAR_MATCH, wm);
```
The object gets received in my custom `WearableListenerService`

```java
@Override
    public void onDataChanged(DataEventBuffer dataEvents) {
        for(DataEvent event : dataEvents) {
            if (event.getDataItem().getUri().getPath().equals(Constant.WEAR_MATCH)) {
                Match match = Packager.unpack(this, event.getDataItem().getData(), Match.class);
            }
        }
    }
```

However I get the `StreamCorruptedException`.
A simple example in your sample on how to use `Bitmap` could help a lot!

Thanks

**Comment by denley** [comment]
`Bitmap` fields can't be sent through the `MessageApi`. You must use the `DataApi`. This is because a `Bitmap` needs to be [transferred as an Asset](https://developer.android.com/training/wearables/data-layer/assets.html).

The following code will successfully transfer the `Bitmap`. While testing this I've found a bug causing the `Bitmap` fields to be null when received with the `@ReceiveData` annotation, but it will currently work fine with the `WearableListenerService`, as in the code below:

```java
Courier.deliverData(GcmReceiverService.this, Constant.WEAR_MATCH, wm);
```

```java
@Override public void onDataChanged(final DataEventBuffer dataEvents) {
    for(DataEvent event : dataEvents) {
        if(event.getDataItem().getUri().getPath().equals(Constant.WEAR_MATCH)) {
            Match match = Packager.unpack(this, event.getDataItem(), Match.class);
        }
    }
}
```
